name: Build and Deploy FBP

on:
  workflow_dispatch:

jobs:
  build-FBP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Build with Ant
        run: ant build

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: FBP
          path: target/

  load-war-file:
    runs-on: ubuntu-latest
    needs: ["build-FBP"]
    steps:
    - name: Download FBP War File
      uses: actions/download-artifact@v5
      with:
        name: FBP
        path: target/*.war
    - name: list target Contents
      run: ls -la target
